# SIEM (Security Information and Event Management)

## 1. What is SIEM?

SIEM (Security Information and Event Management) is a cybersecurity platform that collects, analyzes, and correlates security data from different sources within an organization's IT environment.

It helps Security Operations Center (SOC) teams to:
- Monitor security activity
- Detect threats
- Investigate incidents
- Respond to security events
- Maintain security visibility

Simple definition:

> SIEM collects security logs from different sources, analyzes them for suspicious activity, and generates alerts for SOC analysts to investigate.

---

# 2. Why Organizations Use SIEM

Modern organizations generate large amounts of security data from:

- Endpoints
- Servers
- Firewalls
- Network devices
- Applications
- Cloud services
- User accounts

Without SIEM, security data is scattered across different systems.

SIEM provides:
- Centralized security monitoring
- Faster threat detection
- Easier incident investigation
- Better visibility across the environment
- Compliance reporting support

---

# 3. How SIEM Works

A SIEM workflow:

1. Data Collection
   - Collects logs from different sources such as endpoints, servers, firewalls, and applications.

2. Data Processing
   - Parses and normalizes collected data into a searchable format.

3. Data Analysis
   - Searches for suspicious patterns using detection rules and correlation techniques.

4. Alert Generation
   - Creates alerts when suspicious activities are detected.

5. Investigation and Response
   - SOC analysts investigate alerts, identify threats, and respond accordingly.

---

# 4. Main Components of SIEM

## Log Management

SIEM collects and stores logs from different sources.

Examples:
- Windows Event Logs
- Firewall logs
- Authentication logs
- DNS logs
- Endpoint logs
- Cloud logs

---

## Event Correlation

Event correlation connects multiple related events to identify suspicious activity.

Example:

A user:
- Has multiple failed login attempts
- Successfully logs in from an unusual location
- Accesses sensitive resources

Individually, these events may look normal, but together they may indicate account compromise.

---

## Continuous Monitoring

SIEM continuously monitors security events and provides dashboards and alerts for SOC analysts.

---

## Incident Response

SIEM helps analysts investigate and respond to security incidents.

Typical SOC investigation process:

1. Receive alert
2. Analyze related logs
3. Build event timeline
4. Identify indicators of compromise (IOCs)
5. Determine true positive or false positive
6. Document findings
7. Escalate or respond

---

# 5. Important SIEM Terms

| Term | Meaning |
|---|---|
| Event | A single recorded activity, such as a login attempt |
| Log | A record of activity generated by a system or application |
| Alert | A notification triggered by suspicious activity |
| Correlation | Connecting multiple events to identify attack patterns |
| IOC | Evidence that may indicate malicious activity |
| Detection Rule | A rule used to identify suspicious behavior |

---

# 6. SIEM vs SOC vs Firewall

| Technology | Purpose |
|---|---|
| SIEM | Collects and analyzes security data to detect threats |
| SOC | Security team that monitors, investigates, and responds to threats |
| Firewall | Controls network traffic based on security rules |

A SOC analyst uses SIEM tools to investigate security alerts.

---

# 7. SIEM vs SOAR

| SIEM | SOAR |
|---|---|
| Collects and analyzes security data | Automates security responses |
| Detects threats and generates alerts | Performs automated actions |
| Used for investigation | Used for response automation |

Example:

SIEM detects suspicious login activity.

SOAR can automatically:
- Block an IP address
- Create a ticket
- Notify security teams

---

# 8. Common SIEM Use Cases

## Threat Detection
Detects:
- Brute-force attacks
- Malware activity
- Account compromise
- Insider threats
- Suspicious commands

## Incident Investigation

SOC analysts use SIEM to:
- Search historical logs
- Investigate suspicious activity
- Identify affected systems
- Find attacker indicators

## Compliance Monitoring

SIEM helps organizations:
- Maintain security records
- Generate reports
- Support audits

## Digital Forensics

SIEM helps answer:
- What happened?
- When did it happen?
- Which systems were affected?
- What actions did the attacker perform?

---

# 9. Example SIEM Investigation

Scenario:

Multiple failed login attempts detected.

SOC analyst actions:

1. Search authentication logs
2. Identify affected user account
3. Check source IP address
4. Review successful login attempts
5. Analyze activity after login
6. Identify possible indicators of compromise
7. Decide whether the alert is a true positive or false positive
8. Document findings# SIEM (Security Information and Event Management)

## 1. What is SIEM?

SIEM (Security Information and Event Management) is a cybersecurity platform that collects, analyzes, and correlates security data from different sources within an organization's IT environment.

It helps Security Operations Center (SOC) teams to:
- Monitor security activity
- Detect threats
- Investigate incidents
- Respond to security events
- Maintain security visibility

Simple definition:

> SIEM collects security logs from different sources, analyzes them for suspicious activity, and generates alerts for SOC analysts to investigate.

---

# 2. Why Organizations Use SIEM

Modern organizations generate large amounts of security data from:

- Endpoints
- Servers
- Firewalls
- Network devices
- Applications
- Cloud services
- User accounts

Without SIEM, security data is scattered across different systems.

SIEM provides:
- Centralized security monitoring
- Faster threat detection
- Easier incident investigation
- Better visibility across the environment
- Compliance reporting support

---

# 3. How SIEM Works

A SIEM workflow:

1. Data Collection
   - Collects logs from different sources such as endpoints, servers, firewalls, and applications.

2. Data Processing
   - Parses and normalizes collected data into a searchable format.

3. Data Analysis
   - Searches for suspicious patterns using detection rules and correlation techniques.

4. Alert Generation
   - Creates alerts when suspicious activities are detected.

5. Investigation and Response
   - SOC analysts investigate alerts, identify threats, and respond accordingly.

---

# 4. Main Components of SIEM

## Log Management

SIEM collects and stores logs from different sources.

Examples:
- Windows Event Logs
- Firewall logs
- Authentication logs
- DNS logs
- Endpoint logs
- Cloud logs

---

## Event Correlation

Event correlation connects multiple related events to identify suspicious activity.

Example:

A user:
- Has multiple failed login attempts
- Successfully logs in from an unusual location
- Accesses sensitive resources

Individually, these events may look normal, but together they may indicate account compromise.

---

## Continuous Monitoring

SIEM continuously monitors security events and provides dashboards and alerts for SOC analysts.

---

## Incident Response

SIEM helps analysts investigate and respond to security incidents.

Typical SOC investigation process:

1. Receive alert
2. Analyze related logs
3. Build event timeline
4. Identify indicators of compromise (IOCs)
5. Determine true positive or false positive
6. Document findings
7. Escalate or respond

---

# 5. Important SIEM Terms

| Term | Meaning |
|---|---|
| Event | A single recorded activity, such as a login attempt |
| Log | A record of activity generated by a system or application |
| Alert | A notification triggered by suspicious activity |
| Correlation | Connecting multiple events to identify attack patterns |
| IOC | Evidence that may indicate malicious activity |
| Detection Rule | A rule used to identify suspicious behavior |

---

# 6. SIEM vs SOC vs Firewall

| Technology | Purpose |
|---|---|
| SIEM | Collects and analyzes security data to detect threats |
| SOC | Security team that monitors, investigates, and responds to threats |
| Firewall | Controls network traffic based on security rules |

A SOC analyst uses SIEM tools to investigate security alerts.

---

# 7. SIEM vs SOAR

| SIEM | SOAR |
|---|---|
| Collects and analyzes security data | Automates security responses |
| Detects threats and generates alerts | Performs automated actions |
| Used for investigation | Used for response automation |

Example:

SIEM detects suspicious login activity.

SOAR can automatically:
- Block an IP address
- Create a ticket
- Notify security teams

---

# 8. Common SIEM Use Cases

## Threat Detection
Detects:
- Brute-force attacks
- Malware activity
- Account compromise
- Insider threats
- Suspicious commands

## Incident Investigation

SOC analysts use SIEM to:
- Search historical logs
- Investigate suspicious activity
- Identify affected systems
- Find attacker indicators

## Compliance Monitoring

SIEM helps organizations:
- Maintain security records
- Generate reports
- Support audits

## Digital Forensics

SIEM helps answer:
- What happened?
- When did it happen?
- Which systems were affected?
- What actions did the attacker perform?

---

# 9. Example SIEM Investigation

Scenario:

Multiple failed login attempts detected.

SOC analyst actions:

1. Search authentication logs
2. Identify affected user account
3. Check source IP address
4. Review successful login attempts
5. Analyze activity after login
6. Identify possible indicators of compromise
7. Decide whether the alert is a true positive or false positive
8. Document findings
